// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v3.0.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /home/cw/Downloads/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:451

#ifndef _TAO_IDL_TIMES_SRUZPI_H_
#define _TAO_IDL_TIMES_SRUZPI_H_

#include /**/ "ace/pre.h"

#include "TimeC.h"
#include "tao/PortableServer/Basic_SArguments.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/Fixed_Size_SArgument_T.h"
#include "tao/PortableServer/Var_Size_SArgument_T.h"
#include "tao/PortableServer/Object_SArg_Traits.h"
#include "tao/PortableServer/UB_String_SArguments.h"
#include "tao/PortableServer/get_arg.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/UB_String_Arguments.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

#include "tao/PortableServer/PortableServer.h"
#include "tao/PortableServer/Servant_Base.h"

// TAO_IDL - Generated from
// /home/cw/Downloads/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:66

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // /home/cw/Downloads/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:145

#if !defined (_TIME__SARG_TRAITS_)
#define _TIME__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::Time>
    : public
        Object_SArg_Traits_T<
            ::Time_ptr,
            ::Time_var,
            ::Time_out,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /home/cw/Downloads/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_sh.cpp:73

class POA_Time;
typedef POA_Time *POA_Time_ptr;

class  POA_Time
  : public virtual PortableServer::ServantBase
{
protected:
  POA_Time ();

public:
  /// Useful for template programming.
  typedef ::Time _stub_type;
  typedef ::Time_ptr _stub_ptr_type;
  typedef ::Time_var _stub_var_type;

  POA_Time (const POA_Time& rhs);
  virtual ~POA_Time ();

  virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

  virtual void _dispatch (
      TAO_ServerRequest & req,
      TAO::Portable_Server::Servant_Upcall *servant_upcall);
  
  ::Time *_this ();
  
  virtual const char* _interface_repository_id () const;

  // TAO_IDL - Generated from
  // /home/cw/Downloads/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:36

  virtual ::CORBA::Long current_time (
    void) = 0;

  static void current_time_skel (
      TAO_ServerRequest &server_request,
      TAO::Portable_Server::Servant_Upcall *servant_upcall,
      TAO_ServantBase *servant);

  // TAO_IDL - Generated from
  // /home/cw/Downloads/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:36

  virtual ::CORBA::Long count_requests (
    void) = 0;

  static void count_requests_skel (
      TAO_ServerRequest &server_request,
      TAO::Portable_Server::Servant_Upcall *servant_upcall,
      TAO_ServantBase *servant);

  // TAO_IDL - Generated from
  // /home/cw/Downloads/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:36

  virtual void shutdown (
    void) = 0;

  static void shutdown_skel (
      TAO_ServerRequest &server_request,
      TAO::Portable_Server::Servant_Upcall *servant_upcall,
      TAO_ServantBase *servant);
};

#include /**/ "ace/post.h"

#endif /* ifndef */

